### ISSUE TITLE
flow renders incorrectly for hello-world

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/dashboard#14]
```yaml
!Flow
pods:
  chunk_seg:
    yaml_path: helloworld.crafter.yml
    replicas: $REPLICAS
    read_only: true
  doc_idx:
    yaml_path: helloworld.indexer.doc.yml
  encode:
    yaml_path: helloworld.encoder.yml
    needs: chunk_seg
    replicas: $REPLICAS
  chunk_idx:
    yaml_path: helloworld.indexer.chunk.yml
    replicas: $SHARDS
    separated_workspace: true
  join_all:
    yaml_path: _merge
    needs: [doc_idx, chunk_idx]
    read_only: true
```

gives a wrong rendering

![image](https://user-images.githubusercontent.com/2041322/79689200-898f7c80-8253-11ea-8aae-3fca951807ed.png)

the correct graph should be `join_all` receive outputs from `doc_idx` and `chunk_idx`.
